---
- name: Deploy web app from GitHub
  hosts: web
  become: yes

  vars:
    repo_url: "https://github.com/balajih233/cloudDevops.git"
    project_path: "/var/www/webapp-automation"

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: present

    - name: Clone GitHub repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        force: yes

    - name: Install Python deps
      pip:
        requirements: "{{ project_path }}/requirements.txt"

    - name: Restart webapp
      systemd:
        name: webapp
        state: restarted
        enabled: yes
