---
- name: Deploy web app from GitHub
  hosts: web
  become: yes

  vars:
    repo_url: "https://github.com/balajih233/cloudDevops.git"
    project_path: "/var/www/webapp-automation"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: present

    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        force: yes

    - name: Install Python dependencies (if requirements.txt exists)
      pip:
        requirements: "{{ project_path }}/requirements.txt"
      when: ansible_facts['os_family'] == "Debian"

    - name: Restart webapp service (systemd)
      systemd:
        name: webapp
        state: restarted
        enabled: yes
